### ISSUE TITLE
pyvips installs in ABI mode for osx-arm64

### ISSUE THREAD

**Issue by ollie-bell** [conda-forge/pyvips-feedstock#17]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
Trying to install pyvips using Miniforge on an M1 MacBook. In a clean environment, `conda install pyvips` will install pyvips in ABI mode, and therefore results in the following error when trying to `import pyvips`:

```
>>> import pyvips
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/Caskroom/miniforge/base/envs/test/lib/python3.9/site-packages/pyvips/__init__.py", line 145, in <module>
    _log_handler_cb = ffi.callback('GLogFunc', _log_handler_callback)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/test/lib/python3.9/site-packages/cffi/api.py", line 403, in callback
    return callback_decorator_wrap(python_callable)  # direct mode
  File "/opt/homebrew/Caskroom/miniforge/base/envs/test/lib/python3.9/site-packages/cffi/api.py", line 396, in callback_decorator_wrap
    return self._backend.callback(cdecl, python_callable,
MemoryError: Cannot allocate write+execute memory for ffi.callback(). You might be running on a system that prevents this. For more information, see https://cffi.readthedocs.io/en/latest/using.html#callbacks
```

However, If I first install libvips and the remaining pyvips dependencies via conda, then install pyvips via pip, it correctly installs in API mode. i.e. `conda install libvips cffi pkgconfig && pip install pyvips` seems to work just fine.

Please refer to https://github.com/libvips/pyvips/issues/79#issuecomment-999538145 for some additional discussion

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /opt/homebrew/Caskroom/miniforge/base/envs/test:
#
# Name                    Version                   Build  Channel
atk-1.0                   2.36.0               heb41896_4    conda-forge
boost-cpp                 1.74.0               h128b0ad_5    conda-forge
bzip2                     1.0.8                h3422bc3_4    conda-forge
c-ares                    1.18.1               h3422bc3_0    conda-forge
ca-certificates           2021.10.8            h4653dfc_0    conda-forge
cairo                     1.16.0            hb99c34e_1009    conda-forge
cffi                      1.15.0           py39h52b1de0_0    conda-forge
cfitsio                   4.0.0                h99351b2_0    conda-forge
expat                     2.4.2                hbdafb3b_0    conda-forge
fftw                      3.3.10          nompi_h828537f_102    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.13.1            heb65262_1005    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.10.4               h17b34a0_1    conda-forge
fribidi                   1.0.10               h27ca646_0    conda-forge
gdk-pixbuf                2.42.6               hff60771_0    conda-forge
gettext                   0.19.8.1          h049c9fb_1008    conda-forge
ghostscript               9.54.0               hbdafb3b_1    conda-forge
giflib                    5.2.1                h27ca646_2    conda-forge
glib                      2.70.2               hccf11d3_0    conda-forge
glib-tools                2.70.2               hccf11d3_0    conda-forge
graphite2                 1.3.13            h9f76cd9_1001    conda-forge
graphviz                  2.50.0               h2097151_1    conda-forge
gstreamer-orc             0.4.32               h3422bc3_1    conda-forge
gtk2                      2.24.33              hedeb848_1    conda-forge
gts                       0.7.6                h4b6d4d6_2    conda-forge
harfbuzz                  3.2.0                h6efa254_0    conda-forge
hdf5                      1.12.1          nompi_h829dc4f_103    conda-forge
icu                       69.1                 hbdafb3b_0    conda-forge
imagemagick               7.1.0_18        pl5321hc21dce0_0    conda-forge
jbig                      2.1               h3422bc3_2003    conda-forge
jpeg                      9d                   h27ca646_0    conda-forge
krb5                      1.19.2               hfff258c_3    conda-forge
lcms2                     2.12                 had6a04f_0    conda-forge
lerc                      3.0                  hbdafb3b_0    conda-forge
libcurl                   7.80.0               h8d07098_1    conda-forge
libcxx                    12.0.1               h168391b_0    conda-forge
libdeflate                1.8                  h3422bc3_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h642e427_1    conda-forge
libexif                   0.6.21               h3422bc3_0    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgd                     2.3.3                h6ef1ca9_1    conda-forge
libgfortran               5.0.0.dev0      11_0_1_hf114ba7_23    conda-forge
libgfortran5              11.0.1.dev0         hf114ba7_23    conda-forge
libglib                   2.70.2               h67e64d8_0    conda-forge
libgsf                    1.14.47              h7090ae8_4    conda-forge
libiconv                  1.16                 h642e427_0    conda-forge
libmatio                  1.5.21               h5a20e44_1    conda-forge
libnghttp2                1.43.0               h62a264d_1    conda-forge
libpng                    1.6.37               hf7e6567_2    conda-forge
librsvg                   2.52.5               h957afdb_0    conda-forge
libssh2                   1.10.0               h7a5bd25_2    conda-forge
libtiff                   4.3.0                h74060c4_2    conda-forge
libtool                   2.4.6             hbdafb3b_1008    conda-forge
libvips                   8.12.1               h082f01b_0    conda-forge
libwebp                   1.2.1                h0d20362_0    conda-forge
libwebp-base              1.2.1                h3422bc3_0    conda-forge
libxcb                    1.13              h9b22ae9_1004    conda-forge
libxml2                   2.9.12               hedbfbf4_1    conda-forge
libzlib                   1.2.11            hee7b306_1013    conda-forge
llvm-openmp               12.0.1               hf3c4609_1    conda-forge
lz4-c                     1.9.3                hbdafb3b_1    conda-forge
ncurses                   6.2                  h9aa5885_4    conda-forge
nspr                      4.32                 hbdafb3b_1    conda-forge
nss                       3.73                 h353d031_0    conda-forge
openjpeg                  2.4.0                h062765e_1    conda-forge
openslide                 3.4.1                h71f3ad9_4    conda-forge
openssl                   3.0.0                h3422bc3_2    conda-forge
pango                     1.48.10              h26a1e14_2    conda-forge
pcre                      8.45                 hbdafb3b_0    conda-forge
perl                      5.32.1          1_h9b22ae9_perl5    conda-forge
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h27ca646_0    conda-forge
pkg-config                0.29.2            h144af15_1008    conda-forge
pkgconfig                 1.5.5            py39h2804cbe_1    conda-forge
poppler                   21.11.0              hb0dbcdf_0    conda-forge
poppler-data              0.4.11               hd8ed1ab_0    conda-forge
pthread-stubs             0.4               h27ca646_1001    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
python                    3.9.9           h43b31ca_0_cpython    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pyvips                    2.1.16           py39h5161555_2    conda-forge
readline                  8.1                  hedafd6a_0    conda-forge
setuptools                60.0.4           py39h2804cbe_0    conda-forge
sqlite                    3.37.0               h72a2b83_0    conda-forge
tk                        8.6.11               he1e0b03_1    conda-forge
tzdata                    2021e                he74cb21_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xorg-kbproto              1.0.7             h27ca646_1002    conda-forge
xorg-libice               1.0.10               h27ca646_0    conda-forge
xorg-libsm                1.2.3             h27ca646_1000    conda-forge
xorg-libx11               1.7.2                h3422bc3_0    conda-forge
xorg-libxau               1.0.9                h27ca646_0    conda-forge
xorg-libxdmcp             1.1.3                h27ca646_0    conda-forge
xorg-libxext              1.3.4                h27ca646_1    conda-forge
xorg-libxrender           0.9.10            h27ca646_1003    conda-forge
xorg-libxt                1.2.1                h27ca646_2    conda-forge
xorg-renderproto          0.11.1            h27ca646_1002    conda-forge
xorg-xextproto            7.3.0             h27ca646_1002    conda-forge
xorg-xproto               7.0.31            h27ca646_1007    conda-forge
xz                        5.2.5                h642e427_1    conda-forge
zlib                      1.2.11            hee7b306_1013    conda-forge
zstd                      1.5.0                h861e0a7_0    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : test
    active env location : /opt/homebrew/Caskroom/miniforge/base/envs/test
            shell level : 3
       user config file : /Users/olliebell/.condarc
 populated config files : /opt/homebrew/Caskroom/miniforge/base/.condarc
                          /Users/olliebell/.condarc
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.9.9.final.0
       virtual packages : __osx=12.0.1=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /opt/homebrew/Caskroom/miniforge/base  (writable)
      conda av data dir : /opt/homebrew/Caskroom/miniforge/base/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /opt/homebrew/Caskroom/miniforge/base/pkgs
                          /Users/olliebell/.conda/pkgs
       envs directories : /opt/homebrew/Caskroom/miniforge/base/envs
                          /Users/olliebell/.conda/envs
               platform : osx-arm64
             user-agent : conda/4.11.0 requests/2.26.0 CPython/3.9.9 Darwin/21.1.0 OSX/12.0.1
                UID:GID : 502:20
             netrc file : None
           offline mode : False

```
</details>

**Comment by hmaarrfk** [comment]
maybe we need to add pkg-config as a requirement to the build section when cross compiling.

would you like to update the meta to do that and to check the logs during a build?

**Comment by hmaarrfk** [comment]
I believe I fixed this. Thanks for reporting. Please let me know if it helps.

**Comment by ollie-bell** [comment]
`conda install pyvips` still results in an ABI mode installation for me.

**Comment by hmaarrfk** [comment]
can u please provide the output of `conda list`. i want to make sure you are using build number 2

**Comment by ollie-bell** [comment]
Here you go. Fresh environment with Python 3.9. 

<br/>
Environment (<code>conda list</code>):
<details>

```
# Name                    Version                   Build  Channel
atk-1.0                   2.36.0               heb41896_4    conda-forge
boost-cpp                 1.74.0               h128b0ad_5    conda-forge
bzip2                     1.0.8                h3422bc3_4    conda-forge
c-ares                    1.18.1               h3422bc3_0    conda-forge
ca-certificates           2021.10.8            h4653dfc_0    conda-forge
cairo                     1.16.0            hb99c34e_1009    conda-forge
cffi                      1.15.0           py39h52b1de0_0    conda-forge
cfitsio                   4.0.0                h99351b2_0    conda-forge
expat                     2.4.2                hbdafb3b_0    conda-forge
fftw                      3.3.10          nompi_h828537f_102    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.13.1            heb65262_1005    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.10.4               h17b34a0_1    conda-forge
fribidi                   1.0.10               h27ca646_0    conda-forge
gdk-pixbuf                2.42.6               hff60771_0    conda-forge
gettext                   0.19.8.1          h049c9fb_1008    conda-forge
ghostscript               9.54.0               hbdafb3b_1    conda-forge
giflib                    5.2.1                h27ca646_2    conda-forge
glib                      2.70.2               hccf11d3_1    conda-forge
glib-tools                2.70.2               hccf11d3_1    conda-forge
graphite2                 1.3.13            h9f76cd9_1001    conda-forge
graphviz                  2.50.0               h2097151_1    conda-forge
gstreamer-orc             0.4.32               h3422bc3_1    conda-forge
gtk2                      2.24.33              hedeb848_1    conda-forge
gts                       0.7.6                h4b6d4d6_2    conda-forge
harfbuzz                  3.2.0                h6efa254_0    conda-forge
hdf5                      1.12.1          nompi_h829dc4f_103    conda-forge
icu                       69.1                 hbdafb3b_0    conda-forge
imagemagick               7.1.0_19        pl5321hc21dce0_0    conda-forge
jbig                      2.1               h3422bc3_2003    conda-forge
jpeg                      9d                   h27ca646_0    conda-forge
krb5                      1.19.2               hfff258c_3    conda-forge
lcms2                     2.12                 had6a04f_0    conda-forge
lerc                      3.0                  hbdafb3b_0    conda-forge
libcurl                   7.80.0               h8d07098_1    conda-forge
libcxx                    12.0.1               h168391b_0    conda-forge
libdeflate                1.8                  h3422bc3_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h642e427_1    conda-forge
libexif                   0.6.21               h3422bc3_0    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgd                     2.3.3                h6ef1ca9_1    conda-forge
libgfortran               5.0.0.dev0      11_0_1_hf114ba7_23    conda-forge
libgfortran5              11.0.1.dev0         hf114ba7_23    conda-forge
libglib                   2.70.2               h67e64d8_1    conda-forge
libgsf                    1.14.47              h7090ae8_4    conda-forge
libiconv                  1.16                 h642e427_0    conda-forge
libmatio                  1.5.21               h5a20e44_1    conda-forge
libnghttp2                1.43.0               h62a264d_1    conda-forge
libpng                    1.6.37               hf7e6567_2    conda-forge
librsvg                   2.52.5               h957afdb_0    conda-forge
libssh2                   1.10.0               h7a5bd25_2    conda-forge
libtiff                   4.3.0                h74060c4_2    conda-forge
libtool                   2.4.6             hbdafb3b_1008    conda-forge
libvips                   8.12.1               h082f01b_0    conda-forge
libwebp                   1.2.1                h0d20362_0    conda-forge
libwebp-base              1.2.1                h3422bc3_0    conda-forge
libxcb                    1.13              h9b22ae9_1004    conda-forge
libxml2                   2.9.12               hedbfbf4_1    conda-forge
libzlib                   1.2.11            hee7b306_1013    conda-forge
llvm-openmp               12.0.1               hf3c4609_1    conda-forge
lz4-c                     1.9.3                hbdafb3b_1    conda-forge
ncurses                   6.2                  h9aa5885_4    conda-forge
nspr                      4.32                 hbdafb3b_1    conda-forge
nss                       3.73                 h353d031_0    conda-forge
openjpeg                  2.4.0                h062765e_1    conda-forge
openslide                 3.4.1                h71f3ad9_4    conda-forge
openssl                   3.0.0                h3422bc3_2    conda-forge
pango                     1.48.10              h26a1e14_2    conda-forge
pcre                      8.45                 hbdafb3b_0    conda-forge
perl                      5.32.1          1_h9b22ae9_perl5    conda-forge
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h27ca646_0    conda-forge
pkg-config                0.29.2            h144af15_1008    conda-forge
poppler                   21.11.0              hb0dbcdf_0    conda-forge
poppler-data              0.4.11               hd8ed1ab_0    conda-forge
pthread-stubs             0.4               h27ca646_1001    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
python                    3.9.9           h43b31ca_0_cpython    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pyvips                    2.1.16           py39h5161555_2    conda-forge
readline                  8.1                  hedafd6a_0    conda-forge
setuptools                60.1.1           py39h2804cbe_0    conda-forge
sqlite                    3.37.0               h72a2b83_0    conda-forge
tk                        8.6.11               he1e0b03_1    conda-forge
tzdata                    2021e                he74cb21_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xorg-kbproto              1.0.7             h27ca646_1002    conda-forge
xorg-libice               1.0.10               h27ca646_0    conda-forge
xorg-libsm                1.2.3             h27ca646_1000    conda-forge
xorg-libx11               1.7.2                h3422bc3_0    conda-forge
xorg-libxau               1.0.9                h27ca646_0    conda-forge
xorg-libxdmcp             1.1.3                h27ca646_0    conda-forge
xorg-libxext              1.3.4                h27ca646_1    conda-forge
xorg-libxrender           0.9.10            h27ca646_1003    conda-forge
xorg-libxt                1.2.1                h27ca646_2    conda-forge
xorg-renderproto          0.11.1            h27ca646_1002    conda-forge
xorg-xextproto            7.3.0             h27ca646_1002    conda-forge
xorg-xproto               7.0.31            h27ca646_1007    conda-forge
xz                        5.2.5                h642e427_1    conda-forge
zlib                      1.2.11            hee7b306_1013    conda-forge
zstd                      1.5.1                h861e0a7_0    conda-forge
```

</details>

<br/>

**Comment by hmaarrfk** [comment]
so strange. i mean there was no warning for the ABI.

Unfortunately i don't have a way to test this rapidly. your help with PRs in cross compiling would be greatly appreciated.

To be clear, i think the underlying issue stems from the fact that we are cross compiling arm on x86

**Comment by hmaarrfk** [comment]
I'm going to remove the hacks I introduced in #18 

I think it is a little more complicated than just adding things to `build`.

Hopefully when other linux architectures get pushed through we will be able to debug this more easily.
https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2342

If you are are able to help cross compile, do send some PRs for review

**Comment by ollie-bell** [comment]
I'd be happy to help, but I've never looked in to building conda packages before... so not sure how much use I'll be! If you have a good resource which explains what to do, please send it over.

**Comment by hmaarrfk** [comment]
I guess this is coming up again, but I'm probably going to try to build them in emulation. Without cross compilation.

I'm sorry, I'm no expert with this stuff.

**Comment by hmaarrfk** [comment]
Well tge osx stuff especially

**Comment by hanspinckaers** [comment]
For people googling: the above didn't work for me sadly, this mumbo-jumbo did work, but don't ask me why:

```
conda install libvips cffi pkgconfig && pip install pyvips
pip uninstall cffi
conda install cffi
pip install pyvips --no-cache-dir
```

**Comment by raphaelattias** [comment]
@HansPinckaers the only answer on the internet that actually worked for me, thank you so much! For the first command I had to put the conda channel:

```
conda install --channel conda-forge libvips cffi pkgconfig
pip install pyvips
pip uninstall cffi
conda install cffi
pip install pyvips --no-cache-dir
```
